// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnWsError(arg1:string):Promise<void>;

export function OnWsMessage(arg1:string):Promise<void>;

export function StartBTCPriceWS():Promise<void>;
