// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OnWsError(arg1) {
  return window['go']['main']['App']['OnWsError'](arg1);
}

export function OnWsMessage(arg1) {
  return window['go']['main']['App']['OnWsMessage'](arg1);
}

export function StartBTCPriceWS() {
  return window['go']['main']['App']['StartBTCPriceWS']();
}

export function StopBTCPriceWS() {
  return window['go']['main']['App']['StopBTCPriceWS']();
}
